dist: xenial

language: python

python:
    - "3.6"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install doxygen make default-jre graphviz cmake

install:
    - pip install -r scripts/requirements.txt

script:
    - cd .. && git clone https://github.com/thesofproject/sof.git && cd sof/doc && cmake . && make doc && cd - && cd sof-docs
    - make html
    - ls _build
    - mkdir _build/latest
    - mv -v _build/html/* _build/latest
    - mv _build/latest _build/html
    - touch _build/html/.nojekyll
    - mv scripts/publish-README.md _build/html/README.md
    - mv scripts/publish-index.html _build/html/index.html

deploy:
    - provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      repo: thesofproject/thesofproject.github.io
      on:
        branch: publish
      local_dir: _build/html/
      target_branch: master
