dist: focal

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install doxygen make default-jre graphviz cmake ninja-build


jobs:
    include:

        - name: "Supported scripts/requirements.txt"

          language: python
          python: "3.6"

          install:
              - pip install -r scripts/requirements.txt

          script: &main_script
              - pushd .. && git clone https://github.com/thesofproject/sof.git
                         && pushd sof/doc && cmake -GNinja .
              - popd && popd
              - make html VERBOSE=1
              - ls _build

          before_deploy:
              - mkdir _build/latest
              - mv -v _build/html/* _build/latest
              - mv _build/latest _build/html
              - touch _build/html/.nojekyll
              - mv scripts/publish-README.md _build/html/README.md
              - mv scripts/publish-index.html _build/html/index.html

          deploy:
              - provider: pages
                skip_cleanup: true
                github_token: $GITHUB_TOKEN
                repo: thesofproject/thesofproject.github.io
                on:
                    branch: publish
                local_dir: _build/html/
                target_branch: master


        - name: "PIP_IGNORE_INSTALLED=0 requirements-lax.txt"

          language: minimal

          # Sphinx warnings are not errors any more
          env: LAX=1

          install:
              - sudo apt -y install
                        python3-pip python3-setuptools python3-wheel
                        python3-sphinx python3-breathe python3-docutils
                        python3-sphinx-rtd-theme python3-sphinxcontrib.plantuml

              # Ideally, this pip3 command installs almost nothing.
              - PIP_IGNORE_INSTALLED=0 pip3 install --user
                   -r scripts/requirements-lax.txt

              # sphinx-build < 1.7 doesn't support "auto" and we're not sure
              # all default modules are "thread-safe"
              - sed -i -e '/SPHINXBUILD/ s/-j *auto/-j 1/' Makefile
              # We don't want plantUML to raise the contribution bar
              - sed -i -e 's/^\(plantuml_output_format *=\).*/\1 "none"/' conf.py

          script: *main_script
